spring:
  application:
    name: authorization-server

server:
  port: 8085

eureka:
  instance:
    hostname: localhost

springdoc:
  pathsToMatch: /api/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    resource:
      filter-order: 3
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000